SkillsFundingAgency/dfc-composite-shell

- DFC.Composite.Shell/Services.Regions/UrlRegionService.cs
- DFC.Composite.Shell/Startup.cs
> Dfcc 65-  Added implemtation for UrlRegionService that wires up the azure functions

- DFC.Composite.Shell.Test/ServicesTests/ApplicationServiceTests.cs
- DFC.Composite.Shell.Test/ServicesTests/UrlRewriterTests.cs
- DFC.Composite.Shell/Controllers/ApplicationController.cs
- DFC.Composite.Shell/Services.Application/ApplicationService.cs
- DFC.Composite.Shell/Services.Application/IApplicationService.cs
- DFC.Composite.Shell/Services.Paths/IPathService.cs
- DFC.Composite.Shell/Services.Paths/PathService.cs
Changed ApplicaitonService to only fetch application and not all applications.
Fixed broken tests
> Added getPath to PathService.

- DFC.Composite.Shell/Startup.cs
Update Startup when no help link appsettings exist
> Update Startup when no help link appsettings exist

- Resources/ArmTemplates/parameters.json
Changed variable tokenization from ApimKey to ApimCompositeKey
> NCSD-1930: VSTS variable name change

- Resources/AzureDevOps/azure-pipelines.yml
Added job to test the ARM template as part of the build
> NCSD-1943: Test ARM template in build

- DFC.Composite.Shell.Integration.Test/DFC.Composite.Shell.Integration.Test.csproj
- DFC.Composite.Shell.Integration.Test/appsettings-template.json
- DFC.Composite.Shell.Models/PageViewModel.cs
- DFC.Composite.Shell.Services/Utilities/IVersionedFiles.cs
- DFC.Composite.Shell.Services/Utilities/VersionedFiles.cs
- DFC.Composite.Shell.Test/ServicesTests/ApplicationHealthServiceTests.cs
- DFC.Composite.Shell.Views.Test/DFC.Composite.Shell.Views.Test.csproj
- DFC.Composite.Shell.Views.Test/appsettings-template.json
- DFC.Composite.Shell/Controllers/ApplicationController.cs
- DFC.Composite.Shell/Extensions/VersionedFilesExtensions.cs
- DFC.Composite.Shell/Models/PageViewModelResponse.cs
- DFC.Composite.Shell/Views/Home/Index.cshtml
- DFC.Composite.Shell/Views/Shared/Application/RenderView.cshtml
- DFC.Composite.Shell/Views/Shared/_CookieBanner.cshtml
- DFC.Composite.Shell/Views/Shared/_GovUkHeader.cshtml
- DFC.Composite.Shell/Views/Shared/_JQueryInitialise.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidth.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarLeft.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarRight.cshtml
- DFC.Composite.Shell/Views/Shared/_SkipLink.cshtml
- DFC.Composite.Shell/appsettings-template.json
Added Cookie banner to layouts.
Updated some view unit tests.
> Added link to versioned JS file from GDS CDN to manage the Cookie banner.

- DFC.Composite.Shell/ViewComponents/ListPathsViewComponent.cs
- DFC.Composite.Shell/Views/Shared/_GovUkHeader.cshtml
Removed "Home" menu item
Removed paths from top menu with empty TopNavigationText
> Removed "Home" menu item

- DFC.Composite.Shell/Views/Shared/Components/ShowHelpLinks/Default.cshtml
- PageRegistration/registration.json
Updated registration document to changed label from "How" to "Help"
> Added missing footer.

- DFC.Composite.Shell.Models/Common/Constants.cs
- DFC.Composite.Shell/web.config
Removed server headers and changed name of correlationId
> Removed server headers and changed name of correlationId

- DFC.Composite.Shell.UnitTests/ClientHandlers/CompositeRequestDelegatingHandlerTests.cs
- DFC.Composite.Shell.UnitTests/ClientHandlers/StatusOkDelegatingHandler.cs
- DFC.Composite.Shell/ClientHandlers/CompositeRequestDelegatingHandler.cs
- DFC.Composite.Shell/Extensions/ServiceCollectionExtensions.cs
- DFC.Composite.Shell/Startup.cs
> Added CompositeRequestDelegatingHandler and tests.

- Resources/ArmTemplates/template.json
Added applications insight URL in settings
> Added applications insight URL in settings

- DFC.Composite.Shell/Startup.cs
Added doubleclick.net to allowed image sources in CSP
> Added doubleclick.net to allowed image sources in CSP

- Resources/AzureDevOps/azure-pipelines.yml
Updated the build YAML to produce a separate page registration artifact in the same was as dfc-app-discoverskillsandcareers does
> NCSD-3132: pageregistration

- Resources/ArmTemplates/template.json
Added ApimProxyAddress to the app settings
> NCSD-3163: ApimProxyAddress app setting

- DFC.Composite.Shell.Services/DataProtectionProviders/CompositeDataProtectionDataProvider.cs
- DFC.Composite.Shell.UnitTests/CompositeDataProtectionDataProviders/CompositeDataProtectionDataProviderTests.cs
- Resources/ArmTemplates/template.json
- Fix for 500 error when app with session expired cookie was loaded (CUS-28)
> Release v1.1.36.2

- PageRegistration/registration.json
Removed contact-us as now in its own app registration
> Updated menu text and position

- PageRegistration/registration.json
> Updated menu position

- DFC.Composite.Shell/Views/Shared/_GoogleTagManagerScripts.cshtml
Added correct google tag manger script for using nonce.
> Added correct google tag manger script for using nonce.

- PageRegistration/registration.json
Added menu for careers advise and nulled help to get a job menu so that it does not display in the shell
> Added menu for careers advise and nulled help to get a job

- DFC.Composite.Shell/Startup.cs
Changed adding of response header so that an exception is not thrown if they already exist
> Release v1.1.45.2

- DFC.Composite.Shell/ClientHandlers/CompositeSessionIdDelegatingHandler.cs
- DFC.Composite.Shell/Middleware/CompositeSessionIdMiddleware.cs
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidthNoMain.cshtml
- DFC.Composite.Shell/web.config
- Updated cookie settings. (#245)
- Moved the sign in banner to below the phase banner on FullWidthNoMain layout (#244)
- Static content changes (#243)
Only included the most recent changes to keep this note short, look at PR for detailed full list of changes.
> Release v1.2.22.1

- PageRegistration/registration.json
Removed the legacy (external) find-a-course app registration
> Remove legacy FaC registration

- DFC.Composite.Shell/Startup.cs
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidth.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidthNoMain.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarLeft.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarRight.cshtml
- PageRegistration/registration.json
- Removed external registration for contact-us #288
- Create phase banner landmark #289
- Remove legacy FaC registration #290
- CSP permitted form actions #291
- NCSD-4952-alerts-review #292
> Merge dev to master v1.1.1.1

- DFC.Composite.Shell.Models/Common/Constants.cs
- DFC.Composite.Shell/Startup.cs
Updated security headers to allow media features
> Minor change in csp to allow media features

- DFC.Composite.Shell.UnitTests/Controllers/AuthcontrollerTests.cs
- DFC.Composite.Shell/Controllers/AuthController.cs
- DFC.Composite.Shell/Startup.cs
> Release 1.1.5.2

- PageRegistration/registration.json
- removed all.min.js as now merged into dfcdigtal.min.js #326
> Release 1.1.5.6

- DFC.Composite.Shell/Startup.cs
- Csp Changes to allow Youtube I frames
> Release1.1.5.7

- DFC.Composite.Shell.IntegrationTests/DFC.Composite.Shell.IntegrationTests.csproj
- DFC.Composite.Shell.IntegrationTests/Extensions/IWebHostBuilderExtensions.cs
- DFC.Composite.Shell.IntegrationTests/Framework/ShellTestWebApplicationFactory.cs
- DFC.Composite.Shell.IntegrationTests/Services/TestBannerService.cs
- DFC.Composite.Shell.Services/Application/ApplicationService.cs
- DFC.Composite.Shell.Services/Banner/BannerService.cs
- DFC.Composite.Shell.Services/Banner/IBannerService.cs
- DFC.Composite.Shell.Services/Mapping/ApplicationToPageModelMapper.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/ApplicationServiceTests.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/BannerServiceTests.cs
- DFC.Composite.Shell/DFC.Composite.Shell.csproj
- DFC.Composite.Shell/Policies.Options/BannerClientOptions.cs
- DFC.Composite.Shell/Startup.cs
- DFC.Composite.Shell/Views/Shared/_LayoutBrowserWidth.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidth.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutFullWidthNoMain.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarLeft.cshtml
- DFC.Composite.Shell/Views/Shared/_LayoutSidebarRight.cshtml
- DFC.Composite.Shell/appsettings-template.json
- DFC.Digital.CodeAnalysis.ruleset
- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
- UnitTests.CodeAnalysis.ruleset
> FT2-661 banner integration (#343)

- DFC.Composite.Shell.Services/Application/ApplicationService.cs
- Fix for url format string builder to correctly supply query string #351
> Fix for url format string builder to correctly supply query string

- Resources/AzureDevOps/azure-pipelines.yml
-move integration tests from release to build
-add missing trigger and pr blocks
> move integration tests from release to build

- DFC.Composite.Shell.UnitTests/Controllers/RobotControllerTests.cs
- DFC.Composite.Shell/Controllers/RobotController.cs
- DFC.Composite.Shell/Controllers/SitemapController.cs
- DFC.Composite.Shell/Extensions/HttpRequestExtensions.cs
- Updated robots.txt endpoint to use headers to get host name #379
- Fixed sitemap priority to 0.5 for all routes #380
> Merge/dev to master v.1.1.6.1

- DFC.Composite.Shell.IntegrationTests/Fakes/FakeContentRetriever.cs
- DFC.Composite.Shell.IntegrationTests/appsettings-template.json
- DFC.Composite.Shell.IntegrationTests/appsettings.json
- DFC.Composite.Shell.Services/Application/ApplicationService.cs
- DFC.Composite.Shell.Services/Application/IApplicationService.cs
- DFC.Composite.Shell.Services/ContentRetrieval/ContentRetriever.cs
- DFC.Composite.Shell.Services/ContentRetrieval/IContentRetriever.cs
- DFC.Composite.Shell.Services/ContentRetrieval/PassOnHeaderSettings.cs
- DFC.Composite.Shell.UnitTests/Controllers/ApplicationControllerTests.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/ApplicationServiceTests.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/ContentRetrieverTests.cs
- DFC.Composite.Shell/Controllers/ApplicationController.cs
- DFC.Composite.Shell/Startup.cs
- DFC.Composite.Shell/appsettings-template.json
- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
- Pass on supported headers to CUI apps
> Release 1-1-75-1

- DFC.Composite.Shell.IntegrationTests/DFC.Composite.Shell.IntegrationTests.csproj
- DFC.Composite.Shell.IntegrationTests/Tests/RobotsTests.cs
- DFC.Composite.Shell.IntegrationTests/Tests/ShellRobotFileServiceTests.cs
- DFC.Composite.Shell.Models/Robots/Robot.cs
- DFC.Composite.Shell.Services/ShellRobotFile/IShellRobotFileService.cs
- DFC.Composite.Shell.Services/ShellRobotFile/ShellRobotFileService.cs
- DFC.Composite.Shell.UnitTests/Controllers/AuthcontrollerTests.cs
- DFC.Composite.Shell.UnitTests/Controllers/RobotControllerTests.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/ShellRobotFileServiceTests.cs
- DFC.Composite.Shell/Controllers/AuthController.cs
- DFC.Composite.Shell/Controllers/RobotController.cs
- DFC.Composite.Shell/DFC.Composite.Shell.csproj
- DFC.Composite.Shell/wwwroot/ProductionStaticRobots.txt
- DFC.Composite.Shell/wwwroot/StagingStaticRobots.txt
- DFC.Composite.Shell/wwwroot/StaticRobots.txt
- Stopped robot txt being sent for shell
- Updated Authentication to use the correct error page
> Release 1.1.79.1

- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
Readded variables to the release branch
> ncslt-791: optimizedID

- DFC.Composite.Shell/Startup.cs
- DFC.Composite.Shell/web.config
* added custom header to httpProtocol
* atempt 2
> Adds Release 23 to Release 27

- DFC.Composite.Shell/Views/Shared/_Head.cshtml
- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
* Show noindex on lower environments when AddNoIndexMeta=true
* Update template.json
* Update parameters.json
* Update test-parameters.json
* Fix bing crawling to the lower environment
* Move robots noindex meta to the top
* Added noarchive,nosnippe
* added bingbot crawler
* Test Bing Webmaster
* Remove diallow from Staging
* Remove disallow from ShellRobotFileServiceTests.GetFileTextIdentifiesCorrectResponseForPreProdIntegration
* Remove Disallow from robot tests
* Remove disallow from robot.txt
* roll back robots disallow crawler
---------
> Merge Release 38 to master

- DFC.Composite.Shell/Views/Error/Error.cshtml
- DFC.Composite.Shell/Views/Shared/_Head.cshtml
Release 67.6 contains the following:
AD-182473: [D2] Copy the Crown logo Version Across
> merge Release/live service/67.6 into master

- DFC.Composite.Shell.IntegrationTests/Tests/RobotsTests.cs
- DFC.Composite.Shell.IntegrationTests/Tests/ShellRobotFileServiceTests.cs
- DFC.Composite.Shell.Services/ShellRobotFile/ShellRobotFileService.cs
- DFC.Composite.Shell.UnitTests/ServicesTests/ShellRobotFileServiceTests.cs
- DFC.Composite.Shell/DFC.Composite.Shell.csproj
- DFC.Composite.Shell/wwwroot/StagingStaticRobots.txt
This release contains: 
- AD-189281- INC01536269 - Robots.txt post ASE migration fix
> merge Release/live service/68.1 into master
